version: '3' 

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.go.dev
    tty: true
    volumes:
      - ./src:/go/src/work
    ports: 
      - 8080:8080
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: api
      DB_PORT: 5432
      DB_HOST: db

  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"

volumes:
  postgres: