version: '3' 

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    tty: true
    volumes:
      - ./src:/go/src/github.com/6f-fiber-group-projects/6fg-app-api
    ports: 
      - 8000:8080
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: api
      DB_PORT: 5432
      DB_HOST: db
      ALLOW_ORIGIN: http://localhost:8080
      ADMIN_ID: 1
      VIEWER_ID: 3

  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"

volumes:
  postgres: